config/routes.rb
Rails.application.routes.draw do
  resources :details
  # resources :masters
  root 'home#index'

  resources :masters do
    resources :details
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/detail.rb
class Detail < ApplicationRecord
    belongs_to :master
    validates :description, presence: true
end

app/models/master.rb
class Master < ApplicationRecord
    has_many :details
    validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: %i[ show edit update destroy ]

  # GET /details or /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1 or /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details or /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to detail_url(@detail), notice: "Detail was successfully created." }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1 or /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to detail_url(@detail), notice: "Detail was successfully updated." }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1 or /details/1.json
  def destroy
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to details_url, notice: "Detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def detail_params
      params.require(:detail).permit(:master_id, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  before_action :set_master, only: %i[ show edit update destroy ]

  # GET /masters or /masters.json
  def index
    @masters = Master.all
  end

  # GET /masters/1 or /masters/1.json
  def show
  end

  # GET /masters/new
  def new
    @master = Master.new
  end

  # GET /masters/1/edit
  def edit
  end

  # POST /masters or /masters.json
  def create
    @master = Master.new(master_params)

    respond_to do |format|
      if @master.save
        format.html { redirect_to master_url(@master), notice: "Master was successfully created." }
        format.json { render :show, status: :created, location: @master }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masters/1 or /masters/1.json
  def update
    respond_to do |format|
      if @master.update(master_params)
        format.html { redirect_to master_url(@master), notice: "Master was successfully updated." }
        format.json { render :show, status: :ok, location: @master }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masters/1 or /masters/1.json
  def destroy
    @master.destroy

    respond_to do |format|
      format.html { redirect_to masters_url, notice: "Master was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_master
      @master = Master.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def master_params
      params.require(:master).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/views/details/_form.html.slim
= form_for @detail do |f|
  - if @detail.errors.any?
    #error_explanation
      h2 = "#{pluralize(@detail.errors.count, "error")} prohibited this detail from being saved:"
      ul
        - @detail.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :master_id
    = f.number_field :master_id
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/details/edit.html.slim
h1 Editing detail

== render "form"

=> link_to "Show", @detail
'|
=< link_to "Back", details_path

app/views/details/index.html.slim
h1 Listing details

table
  thead
    tr
      th Master
      th Description
      th
      th
      th

  tbody
    - @details.each do |detail|
      tr
        td = detail.master_id
        td = detail.description
        td = link_to "Show", detail
        td = link_to "Edit", edit_detail_path(detail)
        td = link_to "Destroy", detail, data: {confirm: "Are you sure?"}, method: :delete

br

= link_to "New Detail", new_detail_path

app/views/details/new.html.slim
h1 New detail

== render "form"

= link_to "Back", details_path

app/views/details/show.html.slim
p#notice = notice

p
  strong Master:
  = @detail.master_id

p
  strong Description:
  = @detail.description

=> link_to "Edit", edit_detail_path(@detail)
'|
=< link_to "Back", details_path

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketcircleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/masters/_form.html.slim
= form_for @master do |f|
  - if @master.errors.any?
    #error_explanation
      h2 = "#{pluralize(@master.errors.count, "error")} prohibited this master from being saved:"
      ul
        - @master.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions = f.submit

app/views/masters/edit.html.slim
h1 Editing master

== render "form"

=> link_to "Show", @master
'|
=< link_to "Back", masters_path

app/views/masters/index.html.slim
h1 Listing masters

table
  thead
    tr
      th Name
      th Email
      th
      th
      th

  tbody
    - @masters.each do |master|
      tr
        td = master.name
        td = master.email
        td = link_to "Show", master
        td = link_to "Edit", edit_master_path(master)
        td = link_to "Destroy", master, data: {confirm: "Are you sure?"}, method: :delete

br

= link_to "New Master", new_master_path

app/views/masters/new.html.slim
h1 New master

== render "form"

= link_to "Back", masters_path

app/views/masters/show.html.slim
p#notice = notice

p
  strong Name:
  = @master.name

p
  strong Email:
  = @master.email

=> link_to "Edit", edit_master_path(@master)
'|
=< link_to "Back", masters_path